
# Encomendas
### Get uma encomenda
GET http://localhost:8080/PMEI/api/encomenda/1
Accept: application/json

### Get todas as encomendas
GET http://localhost:8080/PMEI/api/encomenda
Accept: application/json

### Post Criar Encomenda
POST http://localhost:8080/PMEI/monitorizacao/api/encomenda
Accept: application/json
Content-Type: application/json

{
  "customerId": 1,
  "estado": "Despachado",
  "volumes": [
    {
      "produtos": [
        {
          "id": 1,
          "quantidade": 31
        }
      ],
      "tipoEmbalagem": "Caixa cartão",
      "sensores": [
        {
          "tipo": "Temperatura",
          "status": true
        }
      ]
    },
    {
      "produtos": [
        {
          "id": 2,
          "quantidade": 1
        },
        {
          "id": 1,
          "quantidade": 3
        }
      ],
      "tipoEmbalagem": "Caixa cartão com plástico bolha",
      "sensores": [
        {
          "tipo": "Aceleracao",
          "status": true
        },
        {
          "tipo": "Localizacao",
          "status": true
        }
      ]
    }
  ]
}

###

# Clientes
### Get um cliente
GET http://localhost:8080/PMEI/api/cliente/joao
Accept: application/json

### Get todos os clientes
GET http://localhost:8080/PMEI/api/cliente
Accept: application/json

# Volumes
### Get um volume
GET http://localhost:8080/PMEI/api/volume/1
Accept: application/json

### Get todos os volumes
GET http://localhost:8080/PMEI/api/volume
Accept: application/json

# Produtos
### Get um produto
GET http://localhost:8080/PMEI/api/produto/1
Accept: application/json

### Get todos os produtos
GET http://localhost:8080/PMEI/api/produto
Accept: application/json

# Sensores
### Get um sensor
GET http://localhost:8080/PMEI/api/sensor/1
Accept: application/json

### Get todos os sensores
GET http://localhost:8080/PMEI/api/sensor
Accept: application/json

### Get average value  (EP 18)
GET http://localhost:8080/PMEI/api/sensor/1/avg
Accept: application/json

### Get max value  (EP 16)
GET http://localhost:8080/PMEI/api/sensor/1/max
Accept: application/json

### Get min value  (EP 17)
GET http://localhost:8080/PMEI/api/sensor/1/min
Accept: application/json

# Eventos
### Get um evento
GET http://localhost:8080/PMEI/api/evento/1
Accept: application/json

### Get todos os eventos
GET http://localhost:8080/PMEI/api/evento
Accept: application/json